
[Modules]

QRDExt_NativeDemoPlugin_gp = no_cu
QRDExt_JavaDemoPlugin_gp = no_cu
QRDExt_BootRes_gp = no
QRDExt_BrowserQuick_gp = no
QRDExt_BrowserRes_gp = no
QRDExt_BrowserUA_gp = no
QRDExt_WoRead_gp = no
QRDExt_ConfPrompt = no
QRDExt_LanguageGlobalization = yes
QRDExt_BootAnimation_gp = no
QRDExt_LunarService = no
QRDExt_BootLogo_gp = qrd
QRDExt_LauncherRes_gp = no
QRDExt_Extra_Wallpaper_gp = no
QRDExt_CSVT = no
QRDExt_CDROM_RES_gp = no
QRDExt_PreloadApp_gp = no
QRDExt_FilterAppForMonkey_gp = no
QRDExt_ResCustomization_gp = no
QRDExt_DebugCtrl = no
QRDExt_QrdTools = no
QRDExt_HomeLocation = no
QRDExt_WeatherForecast = no
QRDExt_WorldClock = yes
QRDExt_ProfileMgr = no
QRDExt_OSUpdate = yes
QRDExt_CalendarWidget = no
QRDExt_StorageMgr_gp = yes

[Java Feature]

FEATURE_BROWSER_BACK_MENU = yes
FEATURE_BROWSER_HOMEPAGE_MENU = yes
FEATURE_BROWSER_UA_SELECTION = yes
FEATURE_BROWSER_HISTORY_MENU = yes
FEATURE_PROFILE_RINGTONE_SELECTION = yes
FEATURE_CONTACTS_SIMCONTACTS = yes
FEATURE_GLOBALIZATION_BIDI = yes
FEATURE_DOWNLOADPROVIDER_DESTINATION_FOLDER_BY_MIME = yes
FEATURE_DOWNLOADPROVIDER_SUPPORT_BREAKPOINT_CONTINUINGLY = yes
FEATURE_DOWNLOADPROVIDER_MANUAL_PAUSE = yes
FEATURE_ANNUCIATOR_NEW_STATUSBAR_STYLE = yes
FEATURE_CSVT = no
FEATURE_MESSAGE_QUICK_RESPONSE = no
FEATURE_MMS_FILTER_RECIPIENTS_CHARACTER = yes
FEATURE_MMS_MESSAGE_COUNT_LIMIT = yes
FEATURE_MMS_NEW_MESSAGE_NOTIFI_BY_UNREAD = no
FEATURE_HIDE_CHINAUNION_SUPL = yes
FEATURE_STK_USE_CU_SPECIFIC_ICON_STRING = no
FEATURE_GLOBALIZATION_FAST_POWER_OFF = no
FEATURE_GSM_TUNE_AWAY = yes
FEATURE_BAIDU_XCLOUD = no
FEATURE_SHOW_NOTI_IN_THREAD = yes;
FEATURE_SETTINGS_USE_CONTENT_ADAPTIVE_BACKLIGHT = no
FEATURE_ADD_USB_MODE = no;

[Native Feature]
ENABLE_QRDEXT_VIDEO_720P = yes
ENABLE_QRDEXT_AUTO_REG_SMS = yes
ENABLE_QRDEXT_GLOBAL_MODE = no
ENABLE_QRDEXT_CSVT = no

[Java Default Value]
BROWSER_USER_AGENT = "Android/4.1.2-8x25-Solar-Phone-4"

[Native Default Value]
QRDEXT_FLASH_SIZE = 2 * 1024 * 1024 * 1024L
